#!/usr/bin/env bash
#
# Link all my configs to the correct places 
# and set up an arch install from a minimal archinstall profile

SDIR=$(dirname "$0")
SDIR=$(readlink --canonicalize "$SDIR")

ARCH_MAP="input { keyboard { xkb { layout \"gb\"; }; }; }"
NIX_MAP="input { keyboard { xkb { layout \"es\"; }; }; }"

# Flags
START_INDEX=0
IS_ARCH=0
IS_NIX=0
INSTALL_FLATPAK=0

# Flatpak lists
declare -a FLATPAKS=(
    "io.github.kolunmi.Bazaar"
    "io.github.flattool.Warehouse"
    "com.github.tchx84.Flatseal"
    
    "org.pipewire.Helvum"

    "com.usebottles.bottles"
    "md.obsidian.Obsidian"
    "org.kde.ark"

    "com.orama_interactive.Pixelorama"
    "org.gnome.gitlab.YaLTeR.VideoTrimmer"
    "com.authormore.penpotdesktop"
    "io.github.ungoogled_software.ungoogled_chromium"

    "org.prismlauncher.PrismLauncher"
)

declare -a ARCH_FLATPAKS=(
    "org.mozilla.Thunderbird"
    "org.localsend.localsend_app"

    "org.kde.krita"

    "io.github.everestapi.Olympus"
    "com.heroicgameslauncher.hgl"
)

declare -a ARCH_PKGS=(
    # Desktop
    "xdg-desktop-portal-gnome" "niri" "matugen" "dms-shell-bin" "dsearch-bin" "xwayland-satellite"
    "resources" "loupe" "showtime" "decibels" "gcolor3" "gnome-tweaks"
    # Theme
    "adw-gtk-theme" "morewaita-icon-theme"
    # CLI
    "ffmpeg" "zoxide" "bat" "eza" "fastfetch" "less" "yq" "jq" "wl-clipboard" "tealdeer"
    "zsh" "ghostty" "neovim" "oh-my-posh-bin" "zsh-autosuggestions" "zsh-syntax-highlighting"
    # Fonts
    "ttf-fira-code" "ttf-meslo-nerd" "ttf-nunito"
    # Gaming
    "gamemode" "mangohud" "steam"
    # Chat
    "discord" "betterdiscordctl" "beeper-v4-bin" "stoat-desktop-bin" "telegram-desktop"
    # Misc
    "flatpak" "syncthing" "ffmpegthumbnailer" "nodejs" "zen-browser-bin" "android-studio"
)

usage() {
    cat << EOF
Install dotfiles, arch packages, and set up my flake
Usage:
    -a  Installs relevant packages and configurations for Arch Linux
    -n  Installs relevant packages and configurations for NixOS
    -i  Starts a dsearch indexing generation
    -f  Set up flathub and install the usual flatpaks
    -h  Print this usage message
EOF
}

fail() {
    echo "[ERROR] $1"
    exit 1
}

pacman_conf() {
    # Override Arch's stupid ass configs
    sudo ln -sf "$(readlink --canonicalize ../arch/pacman.conf)" /etc/pacman.conf
    sudo ln -sf "$(readlink --canonicalize ../arch/makepkg.conf)" /etc/makepkg.conf
}

install_yay() {
    echo "Installing yay"

    # Make a tmp dir
    mkdir -p "$HOME/tmp"
    cd "$HOME/tmp" || fail "Failed to make tmp folder"
    
    # Clone yay and install
    git clone https://aur.archlinux.org/yay
    cd yay || fail "Failed to clone yay"
    
    # Install base-devel so installation succeeds
    sudo pacman -S --noconfirm base-devel
    
    # Install yay
    makepkg -si --noconfirm
    
    # Clean
    rm -rf "$HOME/tmp"
    
    # Return back to script folder
    cd "$SDIR" || fail "What"
}

arch_user_dirs() {
    echo "Making user dirs"

    if ! xdg-user-dirs-update --help &> /dev/null; then
        yay -S --noconfirm xdg-user-dirs
    fi

    xdg-user-dirs-update
}

arch_pkgs() {
    # Installing gnome stuff
    if ! gdm --help &> /dev/null; then
        yay -S --noconfirm gdm
    fi

    if ! nautilus --help &> /dev/null; then
        yay -S --noconfirm nautilus
    fi
    
    # Install damn near everything else
    yay -S --noconfirm "${ARCH_PKGS[@]}"

    # Set as default shell
    if [[ $SHELL != "/usr/bin/zsh" ]]; then
        chsh -s /usr/bin/zsh
    fi
}

arch_services() {
    echo "Enabling services"
    # GDM
    sudo systemctl enable gdm.service
    # Bluetooth
    sudo systemctl enable bluetooth.service
    # Syncthing
    systemctl --user start syncthing.service
    # Niri
    systemctl --user add-wants niri.service dms.service
    systemctl --user add-wants niri.service dsearch.service
}

arch_cursor() {
    # Make a tmp dir
    mkdir -p "$HOME/tmp"
    cd "$HOME/tmp" || fail "Failed to make tmp folder"

    # Clone and install
    git clone https://github.com/TeddyBearKilla/Afterglow-Cursors-Recolored.git acr
    cd acr/colors/Dracula/Purple || "Failed to clone cursors"

    # cp with no check award goes to
    mkdir -p "$HOME/.local/share/icons"
    ./install.sh
    
    # Clean
    rm -rf "$HOME/tmp"
    
    # Return back to script folder
    cd "$SDIR" || fail "What"
}

setup_flatpak() {
    flatpak --version &> /dev/null || fail "Flatpak is not installed"
    
    echo "Adding flathub repo"
    flatpak remote-add --if-not-exists \
        flathub https://dl.flathub.org/repo/flathub.flatpakrepo

    echo "Installing flatpaks"
    flatpak install --noninteractive "${FLATPAKS[@]}"
    
    if [[ $IS_ARCH == 1 ]]; then
        echo "Installing arch-only flatpaks"
        flatpak install --noninteractive "${ARCH_FLATPAKS[@]}"
    fi
}

install_thumbnailers() {
    # Create folder if it doesn't exist
    sudo mkdir -p /usr/share/thumbnailers/

    sudo ln -sf --target-directory="/usr/share/thumbnailers/" "$(readlink --canonicalize ../thumbnailers/kra.thumbnailer)" /usr/share/thumbnailers/kra.thumbnailer
    sudo ln -sf --target-directory="/usr/share/thumbnailers/" "$(readlink --canonicalize ../thumbnailers/pxo.thumbnailer)" /usr/share/thumbnailers/pxo.thumbnailer
}

niri_config() {
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../niri)" "$HOME/.config/niri"
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../dms)" "$HOME/.config/DankMaterialShell"
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../danksearch)" "$HOME/.config/danksearch"
    
    # Set a default wallpaper if none is set
    if [[ $(dms ipc wallpaper get) != *"dotfiles"* ]]; then
        dms ipc wallpaper set ~/Projects/dotfiles/wallpaper/hos.png
    fi

    if [[ $START_INDEX == 1 ]]; then
        echo "Starting dsearch index"
        systemctl --user start dsearch.service
        dsearch index generate
    fi

    if [[ $IS_ARCH == 1 ]]; then 
        echo "$ARCH_MAP" > "$HOME/.config/niri/keymap.kdl"
    elif [[ $IS_NIX == 1 ]]; then
        echo "$NIX_MAP" > "$HOME/.config/niri/keymap.kdl"
    fi
}

terminal_config() {
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../.zshrc)" "$HOME/.zshrc"
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../oh-my-posh)" "$HOME/.config/oh-my-posh"
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../ghostty)" "$HOME/.config/ghostty"
}

nvim_config() {
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../nvim)" "$HOME/.config/nvim"
}

misc_config() {
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../fastfetch)" "$HOME/.config/fastfetch"
    ln -sf --target-directory="$HOME/.config" "$(readlink --canonicalize ../MangoHud)" "$HOME/.config/MangoHud"
}

arch() {
    # Install git if not installed already
    if ! git -v &> /dev/null; then
        pacman -S --noconfirm git
    fi
    
    pacman_conf 
    install_yay
    arch_user_dirs 
    arch_pkgs
    arch_cursor 
    arch_services 
    install_thumbnailers
}

run() {
    if [[ $IS_ARCH == 1 ]]; then
        arch 
    fi

    if [[ $IS_NIX == 1 ]]; then
        if [[ -d "$HOME/Projects/dotfiles/" ]]; then
            sudo nixos-rebuild switch --flake "$HOME/Projects/dotfiles/nixos/"
        else
            fail "Dotfiles not in ~/Projects"
        fi
    fi
    
    # Create ~/.config if it doesn't exist
    mkdir -p "$HOME/.config/"

    terminal_config 
    niri_config
    nvim_config 
    misc_config 

    if [[ $INSTALL_FLATPAK == 1 ]]; then
        setup_flatpak
    fi
}

main() {
    # Ensure we are on the script's folder so relative paths resolve correctly
    cd "$SDIR" || fail "Path didn't exist"

    local opt OPTIND OPTARG
    while getopts 'inafh' opt; do
        case $opt in
            a) IS_ARCH=1 ;;
            n) IS_NIX=1 ;;
            f) INSTALL_FLATPAK=1 ;;
            i) START_INDEX=1 ;;
            h) usage ; return 0;;
            \?) fail "Unknown flag";;
            *) : ;;
        esac
    done
    shift "$((OPTIND - 1))"

    run
}

main "$@"
