#!/usr/bin/env bash
#
# Sync and flatten media in a deeply nested folder structure

ART_PATH="$HOME/Pictures/Art"
OUT_PATH="$HOME/Pictures/Share"

declare -a EXTENSIONS=("png" "gif" "avif" "jpeg" "jpg")
declare -a FILES=()

usage() {
	local prog=${0##*/}
	cat <<- EOF
	Usage: $prog [options]

	Sync and flatten media in a deeply nested folder structure

	Options:
	    -r	Regenerate the whole sync
	    -d	Start as daemon, listening in the background for changes
	    -s	Single run
	EOF
}

sync-file() {
		local path file
		path="$1"
		file=${path##*/}

		# This works well until two folders of the same name 
		# have files with also the same name
		# A recursive apprach should be done, 
		# but I am too lazy and this should not happen regardless
		if [[ -f "$OUT_PATH/$file" ]]; then
			# If both files are the same, do nothing
			# If they're different, correct the name
			if cmp -s "$path" "$OUT_PATH/$file"; then
				FILES+=("$file")
				:
			else
				local dir dir_name new_name
				# $HOME/Pictures/.../Dir
				dir=$(dirname "$path")
				# Dir
				dir_name=${dir##*/}
				# Dir-File.ext
				new_name="$dir_name-$file"

				echo "Saving $file as $new_name"

				FILES+=("$new_name")
				rsync -at "$path" "$OUT_PATH/$new_name"
			fi
		else
			FILES+=("$file")
			rsync -at "$path" "$OUT_PATH"
		fi
}

clean() {
	for file in "$OUT_PATH"/*; do
		if [[ -f "$file" ]]; then
			local filename=${file##*/}
			if [[ "${FILES[*]}" =~ "$filename" ]]; then
				:
			else
				rm "$OUT_PATH/$filename"
				echo "Cleared $filename"
			fi
		fi
	done
}


walk-tree() {
	local type
	for type in "${EXTENSIONS[@]}"; do
		while IFS= read -r -d $'\0' line; do
			sync-file "$line"
		done < <(find "$ART_PATH" -type f -name "*.$type" -print0)
	done
	clean
}

regenerate() {
	rm -f "$OUT_PATH/*";
	walk-tree 
}

daemon-run() {
	inotifywait -r -m --csv -e modify,create,delete,moved_to,moved_from "$ART_PATH" |
		while IFS=',' read -r dir act file; do
			local ext
			ext=${file##*.}

			# Verify it's extension is in the list
			if [[ "${EXTENSIONS[*]}" =~ "$ext" ]]; then
				case "$act" in
					"MODIFY" | "CREATE" | "MOVED_TO") sync-file "${dir}${file}" ;;
					"DELETE" | "MOVED_FROM")
						local dir_name=${dir##*/}
						if [[ -f "$OUT_PATH/$file" ]]; then
							rm "$OUT_PATH/$file";
						fi
						if [[ -f "$OUT_PATH/${dir_name}-${file}" ]]; then
							rm "$OUT_PATH/${dir_name}-${file}";
						fi
						echo "Cleared $file"
						;;
					*) : ;; # Should never be reached
				esac
			fi
		done
}

main() {
	if [[ ! -d "$OUT_PATH" ]]; then
		mkdir -p "$OUT_PATH"
	fi

	local opt OPTIND OPTARG
	while getopts 'rdsh' opt; do
		case $opt in
			r) regenerate ;;
			d) daemon-run ;;
			s) walk-tree ;;
			h) usage ; return 0;;
			\?) fail "Unknown option";;
			*) usage >&2; return 1;;
		esac
	done
	shift "$((OPTIND - 1))"

	"$@"
}

main "$@"

